# Generated by Django 4.2.14 on 2025-08-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='sensor_type',
            field=models.CharField(choices=[('temp', 'Temperature'), ('humi', 'Humidity'), ('gas', 'Gas Level'), ('batt', 'Battery Level')], help_text='Type of sensor reading', max_length=4),
        ),
    ]
