# Generated by Django 4.2.14 on 2025-08-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_sensorreading_sensor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('temp_high', 'Temperature Too High'), ('temp_low', 'Temperature Too Low'), ('humi_high', 'High Humidity'), ('gas_high', 'High Gas Level'), ('batt_low', 'Low Battery'), ('prox_near', 'Object Too Near'), ('motion_detected', 'Motion Detected')], help_text='Type of alert', max_length=20),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='sensor_type',
            field=models.CharField(choices=[('temp', 'Temperature'), ('humi', 'Humidity'), ('gas', 'Gas Level'), ('batt', 'Battery Level'), ('prox', 'Proximity/Distance'), ('motion', 'Motion/PIR')], help_text='Type of sensor reading', max_length=12),
        ),
    ]
