# Generated by Django 4.2.14 on 2025-08-21 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoring', '0003_alter_alert_alert_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunchbox',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns this lunchbox', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lunchboxes', to=settings.AUTH_USER_MODEL),
        ),
    ]
